### ISSUE TITLE
are raw validations possible?

### ISSUE THREAD

**Issue by bahatron** [flowstudio/datalize#2]
Given I'm not using any route handler. Can i still use this library to validate objects?

for example

```js
// configure validation settings
const validation = datalize([
	field('email', 'E-mail').required().email(),
	field('firstname', 'Firstname').required(),
	field('lastname', 'Lastname').required().trim(),
	field('isTerms').bool(true),
]);

// validation.validate(dataObject) ?
if (validation(dataObject)) {
 // ....
}
```

**Comment by aadamcik** [comment]
@bahatron I've updated the library to support raw data validation. It works as your example, but `validation(dataObject)` is promise so you either have to add `(await validation(dataObject)).isValid` or when you have `autoValidate` option it will throw error, so you have to catch it in try block.
