### ISSUE TITLE
How to use equal Option?

### ISSUE THREAD

**Issue by migumelar** [flowstudio/datalize#3]
I think this is noobish question, I try to use equal but it always gave me an error.

`router.post('/reset', jsonParser, datalize([field('newPassword', 'New Password').length(6,12).required(), field('confirmPassword', 'Confirm Password').length(6,12).equal(field("newPassword")).required() ]), routes.users.resetPassword);
`

I think my code is right but it did not work as expected. Thank you.

**Comment by aadamcik** [comment]
Hi @igumigu ,
`.equal()` takes value that should be compared, e.g. `.equal('string')`.
To make 2 fields equal you will have to use custom filter:
```
.custom(async (value, result) => {
  if (await result.getValue('confirm') !== value) {
    throw new Error('Values must be equal.');
  }
})
```
